services:
  kkotipappapi:
    image: ${DOCKER_REGISTRY-}kkotipappapi
    build:
      context: .
      dockerfile: KkotipAppApi/Dockerfile
    env_file: ".env"
    depends_on:
      database:
        condition: service_healthy
      
  database:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    user: postgres
    environment:
      POSTGRES_PASSWORD: rootPassCHANGEIT
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_data:/var/lib/postgresql/data/pgdata

volumes:
  db_data:
    driver: local
